######################################################################
# Automatically generated by qmake (3.0) Mon Aug 6 22:35:02 2018
######################################################################

TEMPLATE = app
TARGET = src
INCLUDEPATH += .

# Input
SOURCES += \
    main.cpp
