######################################################################
# Automatically generated by qmake (2.01a) Thu Aug 9 19:26:50 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += vector.h
SOURCES += main.cpp
