######################################################################
# Automatically generated by qmake (3.0) Fri Aug 31 16:21:45 2018
######################################################################

TEMPLATE = app
TARGET = src
INCLUDEPATH += .

QMAKE_CXXFLAGS+=-std=c++11
# Input
HEADERS += Array.h Point.h Random.h SO3.h Timer.h
SOURCES += main.cpp
