######################################################################
# Automatically generated by qmake (2.01a) Tue Aug 7 09:25:23 2018
######################################################################

TEMPLATE = app
TARGET =
INCLUDEPATH +=.

# Input
SOURCES += main.cpp inlinecheck.cpp
QMAKE_CXXFLAGS+=-std=c++11
HEADERS += \
    student.h
