######################################################################
# Automatically generated by qmake (3.0) Thu Aug 16 19:34:22 2018
######################################################################

TEMPLATE = app
TARGET = src
INCLUDEPATH += .

QMAKE_CXXFLAGS+=-std=c++11
# Input
HEADERS += Camera.h
SOURCES += main.cpp
