######################################################################
# Automatically generated by qmake (2.01a) Tue Aug 7 14:59:00 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += test.c
