######################################################################
# Automatically generated by qmake (2.01a) Mon Aug 13 18:03:01 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QMAKE_CXXFLAGS+= -std=c++11

# Input
HEADERS += Geometry.h
SOURCES += main.cpp \
    Geometry.cpp
