######################################################################
# Automatically generated by qmake (2.01a) Sat Aug 11 14:15:36 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QMAKE_CXXFLAGS += -std=c++11
# Input
HEADERS += sum_multithread.h
SOURCES += main.cpp sum_multithread.cpp
